//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class OdemeSekliSema {
    
    private OdemeSekliSemaOdemeSekli[] odemeSekliField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OdemeSekli")]
    public OdemeSekliSemaOdemeSekli[] OdemeSekli {
        get {
            return this.odemeSekliField;
        }
        set {
            this.odemeSekliField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class OdemeSekliSemaOdemeSekli {
    
    private string odemeSekliAdiField;
    
    /// <remarks/>
    public string OdemeSekliAdi {
        get {
            return this.odemeSekliAdiField;
        }
        set {
            this.odemeSekliAdiField = value;
        }
    }
}
